sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mjmendez17/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mjmendez17/react-test npm test

after_success:
  - docker build -t mjmendez17/multi-client ./client
  - docker build -t mjmendez17/multi-nginx ./nginx
  - docker build -t mjmendez17/multi-server ./server
  - docker build -t mjmendez17/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub

  #These variables were configured on Travis Website too
  - docker push mjmendez17/multi-client
  - docker push mjmendez17/multi-nginx
  - docker push mjmendez17/multi-server
  - docker push mjmendez17/multi-worker
# ready to deploy


#AS TRAVIS WILL BE INTERACTING WITH AWS, WE HAVE TO PUT SOME CONFIGURATION PARAMETERS:
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-450189179229'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY